name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: yarn install, build
      run: |
        yarn install
        yarn build
      env:
        CI: true
    - name: code coverage
      run: |
        npm install codecov -g
        codecov -f coverage/*.json
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
